"minecraft:wheat" = 0.5
"minecraft:carrot" = 0.5
"minecraft:potato" = 0.5
"minecraft:beetroots" = 0.4
"minecraft:melon" = 0.3
"minecraft:pumpkin" = 0.2
"minecraft:bamboo" = 0.25
"minecraft:cocoa" = 0.25
"minecraft:sweet_berry_bush" = 0.25

"minecraft:coal_ore" = 0.3334
"minecraft:copper_ore" = 0.3334
"minecraft:iron_ore" = 0.625
"minecraft:gold_ore" = 1.25
"minecraft:redstone_ore" = 0.5
"minecraft:lapis_ore" = 0.75
"minecraft:diamond_ore" = 3.0
"minecraft:emerald_ore" = 1.75
"minecraft:nether_quartz_ore" = 0.5
"minecraft:nether_gold_ore" = 1.0
"minecraft:deepslate_coal_ore" = 0.3334
"minecraft:deepslate_copper_ore" = 0.3334
"minecraft:deepslate_iron_ore" = 0.625
"minecraft:deepslate_gold_ore" = 1.25
"minecraft:deepslate_redstone_ore" = 0.5
"minecraft:deepslate_lapis_ore" = 0.75
"minecraft:deepslate_diamond_ore" = 3.0
"minecraft:deepslate_emerald_ore" = 1.75
