"minecraft:endermite" = 0.125
"minecraft:silverfish" = 0.25
"minecraft:slime" = 0.25
"minecraft:piglin" = 0.375
"minecraft:vex" = 0.375
"minecraft:zombie" = 0.375
"minecraft:zombie_villager" = 0.375
"minecraft:magma_cube" = 0.375
"minecraft:phantom" = 0.375
"minecraft:drowned" = 0.375
"minecraft:husk" = 0.375
"minecraft:shulker" = 0.5
"minecraft:skeleton" = 0.5
"minecraft:spider" = 0.5
"minecraft:zombified_piglin" = 0.5
"minecraft:stray" = 0.625
"minecraft:pillager" = 0.625
"minecraft:cave_spider" = 0.625
"minecraft:blaze" = 0.625
"minecraft:creeper" = 0.625
"minecraft:vindicator" = 0.75
"minecraft:enderman" = 0.75
"minecraft:wither_skeleton" = 0.75
"minecraft:guardian" = 0.75
"minecraft:witch" = 1.0
"minecraft:ghast" = 1.0
"minecraft:piglin_brute" = 1.0
"minecraft:illusioner" = 1.25
"minecraft:evoker" = 1.5
"minecraft:hoglin" = 2.5
"minecraft:zoglin" = 2.5
"minecraft:ravager" = 5.0
"minecraft:giant" = 7.5
"minecraft:elder_guardian" = 20.0
"minecraft:warden" = 25.0
"minecraft:wither" = 25.0
"minecraft:ender_dragon" = 35.0
