# FLOWERS

[flowers."minecraft:dandelion"]
value = 0.3
radius = 8
[flowers."minecraft:poppy"]
value = 0.3
radius = 8
[flowers."minecraft:blue_orchid"]
value = 0.4
radius = 8
[flowers."minecraft:allium"]
value = 0.4
radius = 8
[flowers."minecraft:azure_bluet"]
value = 0.3
radius = 8
[flowers."minecraft:red_tulip"]
value = 0.4
radius = 8
[flowers."minecraft:orange_tulip"]
value = 0.4
radius = 8
[flowers."minecraft:white_tulip"]
value = 0.4
radius = 8
[flowers."minecraft:pink_tulip"]
value = 0.4
radius = 8
[flowers."minecraft:oxeye_daisy"]
value = 0.3
radius = 8
[flowers."minecraft:cornflower"]
value = 0.3
radius = 8
[flowers."minecraft:lily_of_the_valley"]
value = 0.3
radius = 8
[flowers."minecraft:torchflower"]
value = 1
radius = 8
[flowers."minecraft:sunflower"]
value = 0.4
radius = 8
[flowers."minecraft:lilac"]
value = 0.4
radius = 8
[flowers."minecraft:rose_bush"]
value = 0.4
radius = 8
[flowers."minecraft:peony"]
value = 0.4
radius = 8
[flowers."minecraft:pitcher_plant"]
value = 1
radius = 8

# LEAVES

[leaves."minecraft:oak_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:spruce_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:birch_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:jungle_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:acacia_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:dark_oak_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:azalea_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:flowering_azalea_leaves"]
value = 0.2
radius = 8
[leaves."minecraft:mangrove_leaves"]
value = 0.1
radius = 8
[leaves."minecraft:cherry_leaves"]
value = 0.2
radius = 8

# OTHER_PLANTS

[other_plants."minecraft:spore_blossom"]
value = 0.3
radius = 12
[other_plants."minecraft:azalea"]
value = 0.3
radius = 12
[other_plants."minecraft:flowering_azalea"]
value = 0.4
radius = 12
[other_plants."minecraft:pink_petals"]
value = 0.4
radius = 6
[other_plants."minecraft:sea_pickle"]
value = 0.2
radius = 6
[other_plants."minecraft:lily_pad"]
value = 0.1
radius = 6
[other_plants."minecraft:waterlily"]
value = 0.1
radius = 6
[other_plants."minecraft:shroomlight"]
value = 0.1
radius = 8

# UTILITIES

["minecraft:beacon"]
value = 1.5
radius = 12
["minecraft:conduit"]
value = 1.25
radius = 12

# CANDLES

[candles."minecraft:candle"]
value = 0.2
radius = 6
[candles."minecraft:white_candle"]
value = 0.2
radius = 6
[candles."minecraft:orange_candle"]
value = 0.2
radius = 6
[candles."minecraft:magenta_candle"]
value = 0.2
radius = 6
[candles."minecraft:light_blue_candle"]
value = 0.2
radius = 6
[candles."minecraft:yellow_candle"]
value = 0.2
radius = 6
[candles."minecraft:lime_candle"]
value = 0.2
radius = 6
[candles."minecraft:pink_candle"]
value = 0.2
radius = 6
[candles."minecraft:gray_candle"]
value = 0.2
radius = 6
[candles."minecraft:light_gray_candle"]
value = 0.2
radius = 6
[candles."minecraft:cyan_candle"]
value = 0.2
radius = 6
[candles."minecraft:purple_candle"]
value = 0.2
radius = 6
[candles."minecraft:blue_candle"]
value = 0.2
radius = 6
[candles."minecraft:brown_candle"]
value = 0.2
radius = 6
[candles."minecraft:green_candle"]
value = 0.2
radius = 6
[candles."minecraft:red_candle"]
value = 0.2
radius = 6
[candles."minecraft:black_candle"]
value = 0.2
radius = 6

# FIRELIGHTS

[fire_lights."minecraft:campfire"]
value = 0.5
radius = 12
[fire_lights."minecraft:soul_campfire"]
value = 0.25
radius = 12
[fire_lights."minecraft:torch"]
value = 0.05
radius = 6
[fire_lights."minecraft:soul_torch"]
value = 0.025
radius = 6
[fire_lights."minecraft:jack_o_lantern"]
value = 0.2
radius = 8
[fire_lights."minecraft:lit_pumpkin"]
value = 0.2
radius = 8
[fire_lights."minecraft:lantern"]
value = 0.2
radius = 8
[fire_lights."minecraft:soul_lantern"]
value = 0.1
radius = 8

# COPPER_BULBS

[glowing_blocks."minecraft:copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:exposed_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:weathered_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:oxidized_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:waxed_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:waxed_exposed_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:waxed_weathered_copper_bulb"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:waxed_oxidized_copper_bulb"]
value = 0.2
radius = 8

# OTHER_GLOWING_BLOCKS

[glowing_blocks."minecraft:end_rod"]
value = 0.1
radius = 6
[glowing_blocks."minecraft:glowstone"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:redstone_lamp"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:sea_lantern"]
value = 0.2
radius = 8
[glowing_blocks."minecraft:pearlescent_froglight"]
value = 0.3
radius = 8
[glowing_blocks."minecraft:verdant_froglight"]
value = 0.3
radius = 8
[glowing_blocks."minecraft:ochre_froglight"]
value = 0.3
radius = 8

# DECORATIONS

[decorations."minecraft:decorated_pot"]
value = 0.1
radius = 4
[decorations."minecraft:painting"]
value = 0.1
radius = 6
