"minecraft:iron_ingot" = 0.25
"minecraft:gold_ingot" = 0.5
"minecraft:netherite_scrap" = 1.0
"minecraft:cooked_porkchop" = 0.25
"minecraft:cooked_beef" = 0.25
"minecraft:cooked_chicken" = 0.25
"minecraft:cooked_rabbit" = 0.25
"minecraft:cooked_mutton" = 0.25
"minecraft:baked_potato" = 0.25
"minecraft:cooked_cod" = 0.25
"minecraft:cooked_salmon" = 0.25
"minecraft:cooked_pufferfish" = 0.25
"minecraft:cooked_tropical_fish" = 0.25
"minecraft:cooked_kelp" = 0.25
